#!/bin/bash -e

IMAGE=$1

container_id=$(docker ps | grep "${IMAGE}:" | awk '{print $1}')

if [ -n "$container_id" ]; then
  docker exec -it $container_id /bin/bash
else
  echo 'No running container to debug'
fi
