#!/bin/bash -e

AWS_PROFILE=$1
IMAGE=$2

AWS_REGION=$(aws --profile $AWS_PROFILE configure get region)

arn=$(aws --profile $AWS_PROFILE --region $AWS_REGION ecs list-tasks --cluster $IMAGE | jq -r '.taskArns[0]')

aws --profile --region $AWS_REGION ecs execute-command --cluster $IMAGE --task "$arn" --interactive --command "/bin/bash"
