#!/bin/bash -e

AWS_PROFILE=$1
IMAGE=$2
PORTS=$3

eval $(print-aws-credentials $AWS_PROFILE)

docker run -d \
  -e AWS_ACCESS_KEY_ID \
  -e AWS_SECRET_ACCESS_KEY \
  -e AWS_REGION \
  -p $PORTS $IMAGE:latest
