#!/bin/bash -e

# Run a local container.
# Initialize env vars in the contaier with the credentials named by <aws-profile>.

if [ -z "$3" ]; then
  echo 'Usage: docker-run <aws-profile> <image> <port-mapping>'
  exit 1
fi


AWS_PROFILE="$1"
IMAGE="$2"
PORTS="$3"

eval $(print-aws-credentials $AWS_PROFILE)

docker run -d \
  -e AWS_ACCESS_KEY_ID \
  -e AWS_SECRET_ACCESS_KEY \
  -e AWS_REGION \
  -p $PORTS $IMAGE:latest
