#!/bin/bash -e

# Kill a local running container

if [ -z "$1" ]; then
  echo 'Usage: docker-kill <image>'
  exit 1
fi

IMAGE="$1"

container_id=$(docker ps | grep "${IMAGE}:" | awk '{print $1}')

if [ -n "$container_id" ]; then
  docker kill $container_id
else
  echo 'No running container to kill'
fi
